// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UongHoangAnh2022033.Data;

#nullable disable

namespace UongHoangAnh2022033.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220328004811_Creatable_UHA1033")]
    partial class Creatable_UHA1033
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("UongHoangAnh2022033.Models.PersonUHA2022033", b =>
                {
                    b.Property<string>("PersonID")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("UongHoangAnh2022033.Models.UHA1033", b =>
                {
                    b.Property<string>("UHAID")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("UHA")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("INTEGER");

                    b.Property<string>("UHAName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("UHAID");

                    b.ToTable("UHA1033");
                });
#pragma warning restore 612, 618
        }
    }
}
